- arguments: [-XQuasiQuotes]
- ignore: {name: "Use &&"}
- ignore: {name: "Use uncurry"}
- ignore: {name: "Use section"}
- ignore: {name: "Use tuple-section"}
# Invalid hint for record field id: https://github.com/ndmitchell/hlint/issues/1383
- ignore: {name: "Redundant id"}
- ignore: {name: "Redundant <$>"}
- ignore: {name: "Avoid lambda using `infix`"}
