roots = [
  "Main.main",
  "ButlerDemos.multiDesktop",
  "ButlerDemos.demoSocialAuth",
  "Butler.Service.Assistant",
  "Butler.Database",
  "Butler.App",
  "^Paths_.*",
  ".*.runTest",
  ".*.test_",
]
type-class-roots = true
