name: butler
version: 0.0.1.0
synopsis: At your service.
description: At your service..
author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
github: TristanCacqueray/butler
language: GHC2021
category: Development
extra-source-files:
  - CHANGELOG.md

ghc-options:
  - -Wall
  - -fwarn-incomplete-uni-patterns
  - -Wno-partial-type-signatures
  - -fwrite-ide-info
  - -hiedir=.hie
  - -Wno-missing-methods

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - ImportQualifiedPost
  - LambdaCase
  - ViewPatterns
  - MultiWayIf
  - QuasiQuotes
  - DeriveGeneric
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - DuplicateRecordFields
  - RecordWildCards
  - OverloadedStrings
  - OverloadedRecordDot
  - TemplateHaskell
  - DataKinds
  - DeriveAnyClass
  - TypeFamilies
  - BlockArguments
  - OverloadedLabels
  - DerivingStrategies
  - PartialTypeSignatures

dependencies:
  - aeson
  - base < 5
  - one-line-aeson-text
  - mmorph
  - binary
  - random
  - mtl
  - optparse-applicative
  - transformers
  - unliftio
  - PyF
  - posix-pty
  - process
  - typed-process
  - with-utf8
  - cgroup-rts-threads

  - witch

  - containers
  - bytestring
  - directory
  - filepath
  - hashable
  - text
  - time
  - uuid
  - unix
  - unix-time
  - network
  - network-run
  - SHA

  - generic-lens
  - lens
  - lens-aeson

  - relude
  #- name: relude
  #  mixin:
  #    - (Relude as Prelude)
  #- name: base
  #  mixin:
  #    - hiding (Prelude)

  # - list-transformer

  - ki
  - ki-unlifted
  - ki-effectful
  - stm
  # - stm-chans

  - serialise
  - cborg
  - cborg-json

  # - effectful
  # - effectful-core
  # - effectful-th
  - servant-websockets

  - websockets
  - servant
  - servant-server
  - servant-auth
  - servant-auth-server
  - http-api-data
  - wai-extra
  - jose

  - retry
  - auto-update

  - wai
  - warp
  - warp-tls
  - HsOpenSSL

  - lucid
  - lucid-htmx
  - lucid-svg
  - http-types
  - servant-lucid
  - tagged
  - case-insensitive

  - chart-svg

  - xstatic
  - xstatic-th
  - servant-xstatic
  - lucid-xstatic

  - xstatic-htmx
  - xstatic-hyperscript
  - xstatic-tailwind
  - xstatic-sakura
  - xstatic-sweetalert2
  - xstatic-remixicon
  - xstatic-xterm
  - xstatic-novnc
  - xstatic-winbox
  - xstatic-pcm-player

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  ghc-options: -threaded -rtsopts -with-rtsopts=-T
  dependencies:
    - butler

tests:
  spec:
    main: Driver.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-T
    source-dirs: test
    dependencies:
      - butler
      - tasty
      - hspec-expectations
      - tasty-hunit
    build-tools: tasty-discover
