name: butler
version: 0.0.1.0
synopsis: At your service.
description: At your service..
author: Tristan Cacqueray
maintainer: tdecacqu@redhat.com
github: TristanCacqueray/butler
language: GHC2021
category: Development
extra-source-files:
  - CHANGELOG.md
  - data/*

ghc-options:
  - -Wall
  - -fwarn-incomplete-uni-patterns
  - -Wno-partial-type-signatures
  - -fwrite-ide-info
  - -Wno-missing-methods

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - ImportQualifiedPost
  - LambdaCase
  - ViewPatterns
  - MultiWayIf
  - QuasiQuotes
  - DeriveGeneric
  - DerivingVia
  - GeneralizedNewtypeDeriving
  - DuplicateRecordFields
  - RecordWildCards
  - OverloadedStrings
  - OverloadedRecordDot
  - TemplateHaskell
  - DataKinds
  - DeriveAnyClass
  - TypeFamilies
  - BlockArguments
  - OverloadedLabels
  - DerivingStrategies
  - PartialTypeSignatures

dependencies:
  # The libraries that come with GHC.
  - base < 5
  - binary
  - bytestring
  - containers
  - directory
  - filepath
  - mtl
  - process
  - stm
  - text
  - time
  - unix

  # SQLite
  - sqlite-simple
  - migrant-core
  - migrant-sqlite-simple

  # CLI
  - with-utf8
  - optparse-applicative

  # A modern prelude
  - unliftio
  - random
  - typed-process
  - attoparsec

  - ki
  - ki-unlifted
  - witch

  # Lens
  - generic-lens
  - lens

  # JSON
  - aeson
  - lens-aeson
  - one-line-aeson-text

  # Network libraries
  - http-api-data
  - network
  - network-run
  - websockets
  - wai
  - warp
  - warp-tls

  # Servant types
  - servant-websockets
  - servant
  - servant-server
  - servant-auth
  - servant-auth-server

  # Extra
  - PyF
  - posix-pty
  - cgroup-rts-threads
  - hashable
  - uuid
  - unix-time
  - serialise
  - jose
  - retry
  - ebml

  # html
  - lucid
  - lucid-htmx
  - lucid-svg
  - http-types
  - servant-lucid

  # xstatics
  - xstatic
  - xstatic-th
  - lucid-xstatic
  - xstatic-htmx
  - xstatic-tailwind
  - xstatic-sweetalert2
  - xstatic-remixicon
  - xstatic-hyperscript
  - xstatic-xterm
  - xstatic-novnc
  - xstatic-winbox
  - xstatic-pcm-player

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: app
  ghc-options: -threaded -rtsopts -with-rtsopts=-T
  dependencies:
    - butler

tests:
  spec:
    main: Driver.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-T
    source-dirs: test
    dependencies:
      - butler
      - tasty
      - hspec-expectations
      - tasty-hunit
    build-tools: tasty-discover
