name: CI
on:
  pull_request: {}
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2.4.0"
      - uses: "cachix/install-nix-action@v20"
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: "cachix/cachix-action@v12"
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: haskell-platform
      - name: Run Test
        run: "nix develop .#ci --command bash -c 'cabal update && ./bin/run-tests'"
